/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author apple
 */
public class MenuUtamaViewAdmin extends javax.swing.JFrame implements View {

    
    private final Color TabActiveColor;
    private final Color TabInactiveColor;
    
    
    public MenuUtamaViewAdmin() {
        this.TabActiveColor = new Color(68,138,255);
        this.TabInactiveColor = new Color(48,63,159);
        initComponents();      
        
    }    

/**
     * Creates new form MenuUtamaView
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTab = new javax.swing.JPanel();
        panelTabBarang = new javax.swing.JPanel();
        BtnBarang = new javax.swing.JButton();
        panelTabTanah = new javax.swing.JPanel();
        btnTanah = new javax.swing.JButton();
        panelTabMutasi = new javax.swing.JPanel();
        btnMutasi = new javax.swing.JButton();
        panelTabLaporan = new javax.swing.JPanel();
        btnLaporan = new javax.swing.JButton();
        panelTabKelolaUser = new javax.swing.JPanel();
        btnKelolaUser = new javax.swing.JButton();
        panelTabLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        panelTabKelolaLainnya = new javax.swing.JPanel();
        btnKelolaLainnya = new javax.swing.JButton();
        panelIsi = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 150, 243));

        panelTab.setBackground(new java.awt.Color(48, 63, 159));
        panelTab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelTab.setForeground(new java.awt.Color(255, 255, 255));

        panelTabBarang.setBackground(new java.awt.Color(48, 63, 159));

        BtnBarang.setBackground(new java.awt.Color(255, 255, 255));
        BtnBarang.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        BtnBarang.setForeground(new java.awt.Color(255, 255, 255));
        BtnBarang.setText("Kelola Barang");
        BtnBarang.setBorder(null);
        BtnBarang.setContentAreaFilled(false);

        javax.swing.GroupLayout panelTabBarangLayout = new javax.swing.GroupLayout(panelTabBarang);
        panelTabBarang.setLayout(panelTabBarangLayout);
        panelTabBarangLayout.setHorizontalGroup(
            panelTabBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTabBarangLayout.setVerticalGroup(
            panelTabBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabBarangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTabTanah.setBackground(new java.awt.Color(48, 63, 159));

        btnTanah.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnTanah.setForeground(new java.awt.Color(255, 255, 255));
        btnTanah.setText("Kelola Tanah");
        btnTanah.setBorder(null);
        btnTanah.setContentAreaFilled(false);

        javax.swing.GroupLayout panelTabTanahLayout = new javax.swing.GroupLayout(panelTabTanah);
        panelTabTanah.setLayout(panelTabTanahLayout);
        panelTabTanahLayout.setHorizontalGroup(
            panelTabTanahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabTanahLayout.createSequentialGroup()
                .addComponent(btnTanah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panelTabTanahLayout.setVerticalGroup(
            panelTabTanahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabTanahLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTanah, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTabMutasi.setBackground(new java.awt.Color(48, 63, 159));

        btnMutasi.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnMutasi.setForeground(new java.awt.Color(255, 255, 255));
        btnMutasi.setText("Kelola Mutasi");
        btnMutasi.setBorder(null);
        btnMutasi.setContentAreaFilled(false);

        javax.swing.GroupLayout panelTabMutasiLayout = new javax.swing.GroupLayout(panelTabMutasi);
        panelTabMutasi.setLayout(panelTabMutasiLayout);
        panelTabMutasiLayout.setHorizontalGroup(
            panelTabMutasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabMutasiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnMutasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panelTabMutasiLayout.setVerticalGroup(
            panelTabMutasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabMutasiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnMutasi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelTabLaporan.setBackground(new java.awt.Color(48, 63, 159));

        btnLaporan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setText("Kelola Laporan");
        btnLaporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLaporan.setContentAreaFilled(false);

        javax.swing.GroupLayout panelTabLaporanLayout = new javax.swing.GroupLayout(panelTabLaporan);
        panelTabLaporan.setLayout(panelTabLaporanLayout);
        panelTabLaporanLayout.setHorizontalGroup(
            panelTabLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabLaporanLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTabLaporanLayout.setVerticalGroup(
            panelTabLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabLaporanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTabKelolaUser.setBackground(new java.awt.Color(48, 63, 159));

        btnKelolaUser.setBackground(new java.awt.Color(255, 255, 255));
        btnKelolaUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnKelolaUser.setForeground(new java.awt.Color(255, 255, 255));
        btnKelolaUser.setText("Kelola User");
        btnKelolaUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnKelolaUser.setContentAreaFilled(false);

        javax.swing.GroupLayout panelTabKelolaUserLayout = new javax.swing.GroupLayout(panelTabKelolaUser);
        panelTabKelolaUser.setLayout(panelTabKelolaUserLayout);
        panelTabKelolaUserLayout.setHorizontalGroup(
            panelTabKelolaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelTabKelolaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTabKelolaUserLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(btnKelolaUser, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        panelTabKelolaUserLayout.setVerticalGroup(
            panelTabKelolaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
            .addGroup(panelTabKelolaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTabKelolaUserLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnKelolaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelTabLogout.setBackground(new java.awt.Color(48, 63, 159));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogout.setContentAreaFilled(false);

        javax.swing.GroupLayout panelTabLogoutLayout = new javax.swing.GroupLayout(panelTabLogout);
        panelTabLogout.setLayout(panelTabLogoutLayout);
        panelTabLogoutLayout.setHorizontalGroup(
            panelTabLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelTabLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabLogoutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelTabLogoutLayout.setVerticalGroup(
            panelTabLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
            .addGroup(panelTabLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabLogoutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
        );

        panelTabKelolaLainnya.setBackground(new java.awt.Color(48, 63, 159));

        btnKelolaLainnya.setBackground(new java.awt.Color(255, 255, 255));
        btnKelolaLainnya.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnKelolaLainnya.setForeground(new java.awt.Color(255, 255, 255));
        btnKelolaLainnya.setText("Kelola Lainnya");
        btnKelolaLainnya.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnKelolaLainnya.setContentAreaFilled(false);

        javax.swing.GroupLayout panelTabKelolaLainnyaLayout = new javax.swing.GroupLayout(panelTabKelolaLainnya);
        panelTabKelolaLainnya.setLayout(panelTabKelolaLainnyaLayout);
        panelTabKelolaLainnyaLayout.setHorizontalGroup(
            panelTabKelolaLainnyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelTabKelolaLainnyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabKelolaLainnyaLayout.createSequentialGroup()
                    .addComponent(btnKelolaLainnya, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelTabKelolaLainnyaLayout.setVerticalGroup(
            panelTabKelolaLainnyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
            .addGroup(panelTabKelolaLainnyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnKelolaLainnya, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTabLayout = new javax.swing.GroupLayout(panelTab);
        panelTab.setLayout(panelTabLayout);
        panelTabLayout.setHorizontalGroup(
            panelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabLayout.createSequentialGroup()
                .addGroup(panelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelTabTanah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTabBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTabMutasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panelTabLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTabKelolaUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTabLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTabKelolaLainnya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTabLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        panelTabLayout.setVerticalGroup(
            panelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTabTanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTabMutasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTabLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTabKelolaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTabKelolaLainnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTabLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelIsi.setBackground(new java.awt.Color(255, 255, 255));
        panelIsi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelIsi.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout panelIsiLayout = new javax.swing.GroupLayout(panelIsi);
        panelIsi.setLayout(panelIsiLayout);
        panelIsiLayout.setHorizontalGroup(
            panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        panelIsiLayout.setVerticalGroup(
            panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTab, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelIsi, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBarang;
    private javax.swing.JButton btnKelolaLainnya;
    private javax.swing.JButton btnKelolaUser;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMutasi;
    private javax.swing.JButton btnTanah;
    private javax.swing.JPanel panelIsi;
    private javax.swing.JPanel panelTab;
    private javax.swing.JPanel panelTabBarang;
    private javax.swing.JPanel panelTabKelolaLainnya;
    private javax.swing.JPanel panelTabKelolaUser;
    private javax.swing.JPanel panelTabLaporan;
    private javax.swing.JPanel panelTabLogout;
    private javax.swing.JPanel panelTabMutasi;
    private javax.swing.JPanel panelTabTanah;
    // End of variables declaration//GEN-END:variables

   public void changetoColorActive(JPanel panel ){
       
       panelTabBarang.setBackground(TabInactiveColor);
       panelTabTanah.setBackground(TabInactiveColor);
       panelTabLaporan.setBackground(TabInactiveColor);
       panelTabMutasi.setBackground(TabInactiveColor);
       panelTabKelolaUser.setBackground(TabInactiveColor);
       panelTabKelolaLainnya.setBackground(TabInactiveColor);
       panelTabLogout.setBackground(TabInactiveColor);
       
       panel.setBackground(TabActiveColor);
   }

    public JButton getBtnBarang() {
        return BtnBarang;
    }

    public JButton getBtnKelolaLainnya() {
        return btnKelolaLainnya;
    }

    public JButton getBtnKelolaUser() {
        return btnKelolaUser;
    }

    public JButton getBtnLaporan() {
        return btnLaporan;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnMutasi() {
        return btnMutasi;
    }

    public JButton getBtnTanah() {
        return btnTanah;
    }

    public JPanel getPanelIsi() {
        return panelIsi;
    }

    public JPanel getPanelTab() {
        return panelTab;
    }

    public JPanel getPanelTabBarang() {
        return panelTabBarang;
    }

    public JPanel getPanelTabKelolaLainnya() {
        return panelTabKelolaLainnya;
    }

    public JPanel getPanelTabKelolaUser() {
        return panelTabKelolaUser;
    }

    public JPanel getPanelTabLaporan() {
        return panelTabLaporan;
    }

    public JPanel getPanelTabLogout() {
        return panelTabLogout;
    }

    public JPanel getPanelTabMutasi() {
        return panelTabMutasi;
    }

    public JPanel getPanelTabTanah() {
        return panelTabTanah;
    }

    
  

    @Override
    public void addListener(ActionListener l) {
        
        BtnBarang.addActionListener(l);
        btnTanah.addActionListener(l);
        btnMutasi.addActionListener(l);
        btnLaporan.addActionListener(l);
        btnKelolaUser.addActionListener(l);
        btnKelolaLainnya.addActionListener(l);
        btnLogout.addActionListener(l);
        
        
    }

    @Override
    public void showMessage(String m) {
    
    }
   
   
   
   
    


    
}
